export const fakeData = {
    results: [
        {
            adult: false,
            backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
            genre_ids: [18, 28, 80, 53],
            id: 155,
            original_language: 'en',
            original_title: 'The Dark Knight',
            overview:
                'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
            popularity: 106.346,
            poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            release_date: '2008-07-14',
            title: 'The Dark Knight',
            video: false,
            vote_average: 8.5,
            vote_count: 26888
        },
        {
            adult: false,
            backdrop_path: '/dXbUVPZnvt4WcQHozLQ5MNXvtwV.jpg',
            genre_ids: [28, 80, 18, 53],
            id: 49026,
            original_language: 'en',
            original_title: 'The Dark Knight Rises',
            overview:
                "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
            popularity: 110.297,
            poster_path: '/85cWkCVftiVs0BVey6pxX8uNmLt.jpg',
            release_date: '2012-07-16',
            title: 'The Dark Knight Rises',
            video: false,
            vote_average: 7.8,
            vote_count: 19047
        },
        {
            adult: false,
            backdrop_path: '/bUQGT4xJib43OrnpmNzgrGaLWJM.jpg',
            genre_ids: [28],
            id: 472027,
            original_language: 'en',
            original_title: 'Batman: The Dark Knight Returns',
            overview:
                'Batman has not been seen for ten years. A new breed of criminal ravages Gotham City, forcing fifty-five-year-old Bruce Wayne back into the cape and cowl, but does he still have what it takes to fight crime in a new era?',
            popularity: 26.435,
            poster_path: '/9uydeANO6PLpD6Irh7qLizaEMjk.jpg',
            release_date: '2013-10-08',
            title: 'Batman: The Dark Knight Returns',
            video: true,
            vote_average: 8.4,
            vote_count: 80
        },
        {
            adult: false,
            backdrop_path: '/1YaG52CwGY3pKh76OBlwX0ymncg.jpg',
            genre_ids: [878, 28, 16, 9648],
            id: 123025,
            original_language: 'en',
            original_title: 'Batman: The Dark Knight Returns, Part 1',
            overview:
                'Batman has not been seen for ten years. A new breed of criminal ravages Gotham City, forcing 55-year-old Bruce Wayne back into the cape and cowl. But, does he still have what it takes to fight crime in a new era?',
            popularity: 43.868,
            poster_path: '/kkjTbwV1Xnj8wBL52PjOcXzTbnb.jpg',
            release_date: '2012-08-21',
            title: 'Batman: The Dark Knight Returns, Part 1',
            video: false,
            vote_average: 7.8,
            vote_count: 1187
        },
        {
            adult: false,
            backdrop_path: '/9Eh5xzWTpJeZM1FGCblWKZ8GTpw.jpg',
            genre_ids: [878, 28, 16, 9648],
            id: 142061,
            original_language: 'en',
            original_title: 'Batman: The Dark Knight Returns, Part 2',
            overview:
                'Batman has stopped the reign of terror that The Mutants had cast upon his city.  Now an old foe wants a reunion and the government wants The Man of Steel to put a stop to Batman.',
            popularity: 29.462,
            poster_path: '/arEZYd6uMOFTILne9Ux0A8qctMe.jpg',
            release_date: '2013-01-03',
            title: 'Batman: The Dark Knight Returns, Part 2',
            video: false,
            vote_average: 8,
            vote_count: 1104
        },
        {
            adult: false,
            backdrop_path: '/9PnKdVpdC7HaNjQLKPygHMT637e.jpg',
            genre_ids: [99],
            id: 29751,
            original_language: 'en',
            original_title: 'Batman Unmasked: The Psychology of the Dark Knight',
            overview:
                'Delve into the world of Batman and the vigilante justice that he brought to the city of Gotham. Batman is a man who, after experiencing great tragedy, devotes his life to an ideal--but what happens when one man takes on the evil underworld alone? Examine why Batman is who he is--and explore how a boy scarred by tragedy becomes a symbol of hope to everyone else.',
            popularity: 16.176,
            poster_path: '/e15wNHmLX7PJUo8lqzQRhwbX7PL.jpg',
            release_date: '2008-07-15',
            title: 'Batman Unmasked: The Psychology of the Dark Knight',
            video: false,
            vote_average: 7.5,
            vote_count: 37
        },
        {
            adult: false,
            backdrop_path: '/lCBDox30tifVepnp4FZUjfdFYw9.jpg',
            genre_ids: [28, 80, 18, 53],
            id: 72003,
            original_language: 'en',
            original_title: 'The Dark Knight',
            overview:
                "In a post-apocalyptic world ravaged by feuding warlords, a group of desperate soldiers hatch a plan to steal a Warlord's treasure and start a new life. Faced with the threat of a horrific death at the hands of the Warlord's executioners, the men escape into a desolate and forbidden land known only as the Shadowlands. Now the men must flee from the Warlord's vicious assassins while defending themselves from the terrifying creatures that inhabit the land.",
            popularity: 2.509,
            poster_path: '/kq4VZAQy30Hs6kQV4NJk1nZHP50.jpg',
            release_date: '2011-07-11',
            title: 'Dark Nemesis',
            video: false,
            vote_average: 6.6,
            vote_count: 5
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [12],
            id: 572515,
            original_language: 'en',
            original_title: 'Dark Knight',
            overview: '',
            popularity: 1.193,
            poster_path: '/95LmwOzfwDMd8KXbDUgGbRLDRDx.jpg',
            release_date: '2000-07-01',
            title: 'Dark Knight',
            video: false,
            vote_average: 2,
            vote_count: 1
        },
        {
            adult: false,
            backdrop_path: '/vc4BgDe25zwpdOm9908MAvjb3PU.jpg',
            genre_ids: [99],
            id: 243238,
            original_language: 'en',
            original_title: 'The Fire Rises: The Creation and Impact of The Dark Knight Trilogy',
            overview:
                'This feature-length documentary delves into the trilogy, opening with the inspiration and vision for the new Batman films and inching its way toward the Rises finale and the culmination of nearly a decade of creative blood, sweat and tears. Candid, thoughtful and extensive, and comprised of revealing behind-the-scenes footage, countless interviews, audition tapes (with Christian Bale and Cillian Murphy doning the cape and cowl), and a narrative grip and momentum all its own, it leaves no stone unturned.',
            popularity: 4.097,
            poster_path: '/y78UlBU4Y2HnEuvSW4V0A5DzP3C.jpg',
            release_date: '2013-09-24',
            title: 'The Fire Rises: The Creation and Impact of The Dark Knight Trilogy',
            video: false,
            vote_average: 6.9,
            vote_count: 15
        },
        {
            adult: false,
            backdrop_path: '/tVBsgjJ37KSuB4dUQAAqfc7h5Jf.jpg',
            genre_ids: [99],
            id: 141559,
            original_language: 'en',
            original_title: 'Legends of the Dark Knight: The History of Batman',
            overview: 'A brief history of the DC Comics character Batman, created by Bob Kane in 1939.',
            popularity: 4.252,
            poster_path: '/ijOIT8msWufRPp1OCVIPIaWgvwc.jpg',
            release_date: '2005-11-15',
            title: 'Legends of the Dark Knight: The History of Batman',
            video: false,
            vote_average: 6.7,
            vote_count: 9
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [28, 80, 18],
            id: 932706,
            original_language: 'en',
            original_title: 'The Dark Knight Legacy',
            overview:
                'A fan film imagining the world after Batman\'s "death" saving Gotham from Bane\'s fusion bomb. Years later, the symbol of Batman is under attack by a new figure using the name to wage a relentless, lethal assault on the criminals of Gotham. It falls to John "Robin" Blake and a young GCPD officer named Stephanie Brown to step up and take back the mantle from the murderous vigilante.',
            popularity: 0.901,
            poster_path: '/aAwxeAzG7pobMK8KTH1MGOTdx6C.jpg',
            release_date: '2019-05-11',
            title: 'The Dark Knight Legacy',
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: '/yY1tj3uSo3jikcQGThn1VCMrCKv.jpg',
            genre_ids: [99, 36],
            id: 369661,
            original_language: 'en',
            original_title: "Masterpiece: Frank Miller's The Dark Knight Returns",
            overview:
                'This is the master-crafted work of the legendary writer and artist Frank Miller. The film encapsulates, and celebrates the stunning achievement of Batman: the Dark Knight Returns, galvanizing the reason why this story ushered in the modern take of the dark and brooding protector of Gotham. This is the journey of Frank Miller, seeking the freedom that some authors only dream of in a lifetime. Narrated by Malcolm McDowell.',
            popularity: 1.497,
            poster_path: '/aWUJ3gcGsm50qMQ8tdUABqKqpMI.jpg',
            release_date: '2013-10-08',
            title: "Masterpiece: Frank Miller's The Dark Knight Returns",
            video: false,
            vote_average: 7,
            vote_count: 1
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [16],
            id: 501972,
            original_language: 'en',
            original_title: 'Batman: The Animated Series -  Tales of the Dark Knight',
            overview: '',
            popularity: 1.96,
            poster_path: '/9copibWIXwQSCJHQLJdokE7dwCj.jpg',
            release_date: '',
            title: 'Batman: The Animated Series -  Tales of the Dark Knight',
            video: true,
            vote_average: 9,
            vote_count: 2
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [28],
            id: 928225,
            original_language: 'en',
            original_title: 'BATMAN: THE DARK KNIGHT RETURNS',
            overview: 'A 2016 fan film based off the storyline of the same name.',
            popularity: 0.966,
            poster_path: '/8pUfb7dii95y3ufBZ7vYA24drMV.jpg',
            release_date: '2016-11-23',
            title: 'BATMAN: THE DARK KNIGHT RETURNS',
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 745984,
            original_language: 'en',
            original_title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight - Batman Unbound',
            overview: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight - Batman Unbound',
            popularity: 2.793,
            poster_path: '/vwhH1T73DwCLkICuz0e7lTeRCCM.jpg',
            release_date: '',
            title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight - Batman Unbound',
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: '/bvjanIWMmcHVxYmVmTwXKPCPpQe.jpg',
            genre_ids: [99],
            id: 204651,
            original_language: 'en',
            original_title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight',
            overview:
                'A six-part documentary primarily chronicling Warner Bros. Studios adaptations of the DC Comics character Batman, from 1989–1997. First premiered on the special features discs of the Batman Motion Picture Anthology DVD set.',
            popularity: 1.988,
            poster_path: '/4Id0fPgPp7dHWJbftGjorawN11k.jpg',
            release_date: '2005-10-18',
            title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight',
            video: false,
            vote_average: 7.3,
            vote_count: 8
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 936912,
            original_language: 'en',
            original_title: 'The Dark Knight: The Ballad of the N Word',
            overview: 'The Dark Knight stops the Joker from being racist.',
            popularity: 0.6,
            poster_path: null,
            release_date: '',
            title: 'The Dark Knight: The Ballad of the N Word',
            video: false,
            vote_average: 0,
            vote_count: 0
        },
        {
            adult: false,
            backdrop_path: '/mWIsvElXLgzjYKrv3Yy3i4y1RxL.jpg',
            genre_ids: [28, 16, 80, 10770],
            id: 377531,
            original_language: 'en',
            original_title: "The Dark Knight's First Night",
            overview:
                '"The Dark Knight\'s First Night" is the name given to the short two-minute pilot used by Bruce Timm and Eric Radomski to show Fox executives what they were planning to do with "Batman: The Animated Series".',
            popularity: 1.391,
            poster_path: '/zBx5oTDO0kNEb5hr420AOuz7PL9.jpg',
            release_date: '1991-01-12',
            title: "The Dark Knight's First Night",
            video: false,
            vote_average: 8.6,
            vote_count: 15
        },
        {
            adult: false,
            backdrop_path: '/6wHTzsvzm3KKYM8c2Z81mzfkhDu.jpg',
            genre_ids: [14, 28, 12],
            id: 257171,
            original_language: 'ja',
            original_title: '呀〈KIBA〉 ～暗黒騎士鎧伝～',
            overview:
                "The spirit of Kiba the Dark Makai Knight influenced everything since the beginning. Though he called himself a Makai Knight, Kiba was no different to a Horror. Kiba's spirit resides inside what was once a grey colored Makai Armor that's filled with the dark knowledge of Makai Power. As Barago absorbed Horror after Horror, Kiba eventually deformed into an organically pure black armor with a cape. Kiba assumed full control over his host upon Meisha's defeat by Kouga.",
            popularity: 4.509,
            poster_path: '/nCZCm6JKjgwrvrjP4YbGBLm7C3x.jpg',
            release_date: '2011-09-03',
            title: 'Garo - Kiba: The Dark Knight',
            video: false,
            vote_average: 5.6,
            vote_count: 7
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 745316,
            original_language: 'en',
            original_title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight - Dark Side of the Knight',
            overview: 'An overview of the making of Batman Returns (1992).',
            popularity: 0.6,
            poster_path: '/p5mi0ZH5aElLgflK9ahabdtfvnW.jpg',
            release_date: '2005-10-18',
            title: 'Shadows of the Bat: The Cinematic Saga of the Dark Knight - Dark Side of the Knight',
            video: false,
            vote_average: 0,
            vote_count: 0
        }
    ]
};
